packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@eslint/js": ^9.38.0
  "@supabase/auth-helpers-nextjs": ^0.10.0
  "@supabase/supabase-js": ^2.95.2
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  "@trpc/client": ^11.9.0
  "@trpc/server": ^11.9.0
  "@trpc/tanstack-react-query": ^11.9.0
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 5.1.0
  eslint: ^9.38.0
  hono: ^4.11.4
  prettier: ^3.6.2
  prisma: ^7.3.0
  "@prisma/client": ^7.3.0
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12
  zustand: ^5.0.10
  vite: 7.1.12

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
