import Link from "next/link";

import { Button } from "@dubai/ui/button";
import { ZoneProvider } from "@dubai/ui/zones";

export default function HomePage() {
  return (
    <main className="min-h-screen">
      {/* Navigation */}
      <nav className="border-border/40 sticky top-0 z-50 border-b backdrop-blur-sm">
        <div className="container flex h-16 items-center justify-between">
          <span className="text-xl font-bold tracking-tight">
            Dubai <span className="text-primary">Furnishing</span>
          </span>
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="sm" asChild>
              <Link href="/login">Sign in</Link>
            </Button>
            <Button size="sm" asChild>
              <Link href="/register">Get Started</Link>
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <ZoneProvider zone="warmth">
        <section className="container flex flex-col items-center gap-6 pb-16 pt-24 text-center md:pt-32">
          <h1 className="max-w-3xl text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
            AI-Powered Interior Design for Your{" "}
            <span className="text-primary">Dubai Home</span>
          </h1>
          <p className="text-muted-foreground max-w-2xl text-lg leading-relaxed">
            Upload a photo of your room, set your budget, and let our AI curate
            personalised furniture packages from verified Dubai retailers —
            delivered straight to your door.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4 pt-2">
            <Button size="lg" asChild>
              <Link href="/register">Get Started</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/gallery">Browse Gallery</Link>
            </Button>
          </div>
        </section>
      </ZoneProvider>

      {/* Features */}
      <section className="bg-muted/50 border-border/40 border-y py-20">
        <div className="container">
          <h2 className="mb-12 text-center text-3xl font-bold tracking-tight">
            Everything You Need to Furnish Smarter
          </h2>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            <div className="bg-background rounded-xl border p-6 shadow-sm">
              <div className="bg-primary/10 text-primary mb-4 flex h-12 w-12 items-center justify-center rounded-lg text-2xl">
                ✨
              </div>
              <h3 className="mb-2 text-lg font-semibold">AI Room Design</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                Upload photos of your space and receive personalised furniture
                packages generated by our AI to match your style and dimensions.
              </p>
            </div>

            <div className="bg-background rounded-xl border p-6 shadow-sm">
              <div className="bg-primary/10 text-primary mb-4 flex h-12 w-12 items-center justify-center rounded-lg text-2xl">
                🛋️
              </div>
              <h3 className="mb-2 text-lg font-semibold">
                Curated Marketplace
              </h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                Browse quality furniture sourced from verified Dubai retailers,
                all in one place with transparent pricing and reviews.
              </p>
            </div>

            <div className="bg-background rounded-xl border p-6 shadow-sm">
              <div className="bg-primary/10 text-primary mb-4 flex h-12 w-12 items-center justify-center rounded-lg text-2xl">
                🚚
              </div>
              <h3 className="mb-2 text-lg font-semibold">
                White-Glove Delivery
              </h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                Schedule delivery at a time that suits you. Our team handles
                assembly and placement across Dubai and the UAE.
              </p>
            </div>

            <div className="bg-background rounded-xl border p-6 shadow-sm">
              <div className="bg-primary/10 text-primary mb-4 flex h-12 w-12 items-center justify-center rounded-lg text-2xl">
                💰
              </div>
              <h3 className="mb-2 text-lg font-semibold">Smart Budgeting</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">
                Set your budget preferences and our AI builds packages that fit,
                so you never overspend while still getting great design.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="container py-20">
        <h2 className="mb-12 text-center text-3xl font-bold tracking-tight">
          How It Works
        </h2>
        <div className="grid gap-10 md:grid-cols-3">
          <div className="flex flex-col items-center text-center">
            <div className="bg-primary text-primary-foreground mb-4 flex h-14 w-14 items-center justify-center rounded-full text-xl font-bold">
              1
            </div>
            <h3 className="mb-2 text-lg font-semibold">
              Upload Your Room Photos
            </h3>
            <p className="text-muted-foreground text-sm leading-relaxed">
              Snap a few photos of the room you want to furnish. Our AI analyses
              dimensions, lighting, and existing decor.
            </p>
          </div>

          <div className="flex flex-col items-center text-center">
            <div className="bg-primary text-primary-foreground mb-4 flex h-14 w-14 items-center justify-center rounded-full text-xl font-bold">
              2
            </div>
            <h3 className="mb-2 text-lg font-semibold">
              Get AI-Curated Packages
            </h3>
            <p className="text-muted-foreground text-sm leading-relaxed">
              Receive multiple furniture packages tailored to your taste and
              budget, with 3D previews so you can see how everything fits.
            </p>
          </div>

          <div className="flex flex-col items-center text-center">
            <div className="bg-primary text-primary-foreground mb-4 flex h-14 w-14 items-center justify-center rounded-full text-xl font-bold">
              3
            </div>
            <h3 className="mb-2 text-lg font-semibold">
              Order &amp; Get It Delivered
            </h3>
            <p className="text-muted-foreground text-sm leading-relaxed">
              Pick your favourite package, place the order, and we handle the
              rest — from warehouse to white-glove delivery at your door.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Banner */}
      <section className="bg-primary text-primary-foreground py-16">
        <div className="container flex flex-col items-center gap-6 text-center">
          <h2 className="max-w-xl text-3xl font-bold tracking-tight">
            Ready to Transform Your Space?
          </h2>
          <p className="max-w-lg text-sm opacity-90">
            Join thousands of Dubai residents who have redesigned their homes
            with AI-powered furniture curation. It takes less than 5 minutes to
            get started.
          </p>
          <Button size="lg" variant="secondary" asChild>
            <Link href="/register">Create Free Account</Link>
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-border/40 border-t py-12">
        <div className="container grid gap-8 sm:grid-cols-2 md:grid-cols-4">
          <div>
            <span className="mb-3 block text-lg font-bold">
              Dubai <span className="text-primary">Furnishing</span>
            </span>
            <p className="text-muted-foreground text-sm">
              AI-powered interior design and furniture delivery across Dubai and
              the UAE.
            </p>
          </div>

          <div>
            <h4 className="mb-3 font-semibold">Product</h4>
            <ul className="text-muted-foreground space-y-2 text-sm">
              <li>
                <Link
                  href="/gallery"
                  className="hover:text-foreground transition-colors"
                >
                  Gallery
                </Link>
              </li>
              <li>
                <Link
                  href="/packages"
                  className="hover:text-foreground transition-colors"
                >
                  Packages
                </Link>
              </li>
              <li>
                <Link
                  href="/pricing"
                  className="hover:text-foreground transition-colors"
                >
                  Pricing
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="mb-3 font-semibold">Company</h4>
            <ul className="text-muted-foreground space-y-2 text-sm">
              <li>
                <Link
                  href="/about"
                  className="hover:text-foreground transition-colors"
                >
                  About
                </Link>
              </li>
              <li>
                <Link
                  href="/contact"
                  className="hover:text-foreground transition-colors"
                >
                  Contact
                </Link>
              </li>
              <li>
                <Link
                  href="/careers"
                  className="hover:text-foreground transition-colors"
                >
                  Careers
                </Link>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="mb-3 font-semibold">Legal</h4>
            <ul className="text-muted-foreground space-y-2 text-sm">
              <li>
                <Link
                  href="/privacy"
                  className="hover:text-foreground transition-colors"
                >
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link
                  href="/terms"
                  className="hover:text-foreground transition-colors"
                >
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="container mt-8 border-t pt-6">
          <p className="text-muted-foreground text-center text-sm">
            &copy; 2026 Dubai Furnishing. All rights reserved.
          </p>
        </div>
      </footer>
    </main>
  );
}
